/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stable_matching_grupo02_esd115;

import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author HP
 */
public class InfoEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form InfoEmpresa
     */
    public InfoEmpresa() {
        initComponents();
        inicializarColumnas();
    }
 private void inicializarColumnas() {
 TableColumnModel tColumnModel = new DefaultTableColumnModel();
 for (int i = 0; i < 7; i++) {
    TableColumn col = new TableColumn(i);
    switch (i) {
            case 0:
            col.setHeaderValue("nombre");
            break;
            case 1:
            col.setHeaderValue("profecion requerida");
            break;
            case 2:
            col.setHeaderValue("plazas disponibles");
            break;
            case 3:
            col.setHeaderValue("experiencia requerida");
            break;
            case 4:
            col.setHeaderValue("preferencias");
            break;
            case 5:
            col.setHeaderValue("telefono");
            break;
            case 6:
            col.setHeaderValue("direccion");
            break;
            
 }
    tColumnModel.addColumn(col);
 }
    TModel.setColumnModel(tColumnModel);
 }
    
    
    private void agregarDatos(){


DefaultTableModel modelo = (DefaultTableModel)TModel.getModel();



String datos[] = new String[9];//ARRAY DE 4
STABLE_MATCHING empresa = new STABLE_MATCHING();
//LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST 


for (int i = 0; i <  empresa.emp.size(); i++) {



datos[0] = empresa.emp.get(i).getNombre();
datos[1] = empresa.emp.get(i).getProfesionRequerida();
datos[2] = String.valueOf(empresa.emp.get(i).getPlazaDisponible());
datos[3] = String.valueOf(empresa.emp.get(i).getExperienciaRequerida());
datos[4] = String.valueOf( empresa.emp.get(i).getPreferencias());
datos[5] = empresa.emp.get(i).getTelefono();
datos[6] = empresa.emp.get(i).getDireccion();

modelo.addRow(datos);
}
TableColumn colum1 = null;
colum1 = TModel.getColumnModel().getColumn(0);
colum1.setPreferredWidth(60);

TableColumn colum2 = null;
colum2 = TModel.getColumnModel().getColumn(1);
colum2.setPreferredWidth(5);

TableColumn colum3 = null;
colum3 = TModel.getColumnModel().getColumn(2);
colum3.setPreferredWidth(40);
colum3.setPreferredWidth(10);

TableColumn colum4 = null;
colum4 = TModel.getColumnModel().getColumn(3);
colum4.setPreferredWidth(10);

TableColumn colum5 = null;
colum5 = TModel.getColumnModel().getColumn(4);
colum5.setPreferredWidth(100);

TableColumn colum6 = null;
colum6 = TModel.getColumnModel().getColumn(5);
colum6.setPreferredWidth(5);

TableColumn colum7 = null;
colum7 = TModel.getColumnModel().getColumn(6);
colum7.setPreferredWidth(40);
colum7.setPreferredWidth(10);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TModel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4","Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(TModel);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agregarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TModel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
